language: ruby
rvm:
  - 2.5.3
  - 2.6.0
  - 2.7.5

stages:
  - code-quality
  - test

jobs:
  include:
    - rvm: 2.5.3
      stage: code-quality
      script: bundle exec rubocop
    - rvm: 2.5.3
      stage: test
      script: bundle exec rspec
    - rvm: 2.6.0
      stage: code-quality
      script: bundle exec rubocop
    - rvm: 2.6.0
      stage: test
      script: bundle exec rspec
    - rvm: 2.7.5
      stage: code-quality
      script: bundle exec rubocop
    - rvm: 2.7.5
      stage: test
      script: bundle exec rspec
